common: &common
    access_key_id: 
    secret_access_key: 

development:
    <<: *common
    bucket: csoffice

test:
    <<: *common
    bucket: csoffice

production:
    <<: *common
    bucket: csoffice
    


